import Image from 'next/image'
import Link from 'next/link'
import { products } from '@/data/products'
import { Button } from '@/components/ui/button'

export function HeroSection(){return <section className='section-wrap pt-12'><div className='relative overflow-hidden rounded-3xl border border-white/10 bg-surface p-8 md:p-14'><div className='absolute -right-20 -top-20 h-72 w-72 rounded-full bg-accent-violet/30 blur-3xl'/><p className='text-xs uppercase tracking-[0.2em] text-white/70'>Street Performance Overgrips</p><h1 className='mt-4 text-4xl font-black leading-tight md:text-7xl'>YOUR RACQUET.<br/>YOUR STYLE.</h1><p className='mt-4 max-w-xl text-white/70'>Premium collectible overgrips blending tennis performance with modern streetwear energy.</p><div className='mt-8 flex gap-3'><Button href='/collections'>Shop Grips</Button><Button href='/subscription' variant='ghost'>Build Your Pack</Button></div><div className='mt-10 grid gap-4 md:grid-cols-3'>{products.map(p=><div key={p.id} className='rounded-2xl border border-white/10 bg-black/30 p-3'><Image src={p.images[0]} alt={p.name} width={500} height={500} className='h-40 w-full rounded-xl object-cover'/><p className='mt-2 font-semibold'>{p.name}</p></div>)}</div></div></section>}

export function ContentSections(){return <>
<section className='section-wrap grid gap-6 md:grid-cols-3'>{['Featured Collections','Why Players Switch','Performance Benefits'].map((t,i)=><div key={t} className='rounded-2xl border border-white/10 bg-surface p-6 hover:-translate-y-1 transition'><h3 className='text-xl font-bold'>{t}</h3><p className='mt-2 text-white/70'>{i===0?'Wildline, Core Mono, and limited drops built for style-led athletes.':i===1?'From boring white grips to bold textures that complete your look.':'Sweat absorption, comfort, tackiness, and durability tuned for match play.'}</p></div>)}</section>
<section className='section-wrap'><div className='rounded-3xl border border-white/10 bg-gradient-to-r from-accent-violet/20 to-accent-cyan/20 p-10'><h2 className='text-3xl font-black'>Subscribe & Save 20%</h2><p className='mt-2 text-white/80'>Monthly curated grip drops, early access colorways, and bundle pricing.</p><Button href='/subscription'>Start Subscription</Button></div></section>
<section className='section-wrap grid gap-8 md:grid-cols-2'><div><h3 className='text-2xl font-black'>Player Reviews</h3><p className='mt-4 text-white/70'>“Best feeling grip I have used, and people ask about it every match.” — Riya P.</p></div><div><h3 className='text-2xl font-black'>@OVERGRIP Social Feed</h3><p className='mt-4 text-white/70'>Instagram & TikTok-ready visuals with athlete + creator collabs.</p></div></section>
<section className='section-wrap'><div className='rounded-2xl border border-white/10 p-8 text-center'><h3 className='text-2xl font-black'>Get drop alerts</h3><p className='text-white/70'>New colorways. Limited releases. Member-only bundles.</p><div className='mx-auto mt-5 flex max-w-md gap-2'><input className='w-full rounded-full bg-white/5 px-4 py-3' placeholder='Email address'/><button className='rounded-full bg-accent-fuchsia px-5 font-semibold'>Join</button></div></div></section>
</>}

export function ProductGrid(){return <section className='section-wrap'><h1 className='text-4xl font-black'>Collections</h1><div className='mt-8 grid gap-6 md:grid-cols-3'>{products.map(p=><Link key={p.id} href={`/products/${p.slug}`} className='rounded-2xl border border-white/10 p-3 hover:border-accent-cyan'><Image src={p.images[0]} alt={p.name} width={500} height={500} className='h-56 w-full rounded-xl object-cover'/><p className='mt-3 font-bold'>{p.name}</p><p className='text-white/70'>{p.colorway}</p><p className='text-accent-neon'>${p.price}</p></Link>)}</div></section>}
